# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11YqgBKwF87fC7xurdyo1NcLTk2VvWs8L
"""

student_name = input("Enter student name: ")
total_classes = int(input("Enter total classes held: "))
classes_attended = int(input("Enter classes attended: "))


if total_classes <= 0:
    print("Total classes must be greater than 0.")
elif classes_attended > total_classes:
    print("Classes attended cannot be greater than total classes.")
else:
    attendance = (classes_attended / total_classes) * 100

    print("\nStudent Name:", student_name)
    print("Attendance Percentage:", round(attendance, 2), "%")

if attendance >= 75:
  print("Allowed for exam")
else:
  print("Not allowed for exam")